import type { BountyDefinition } from './types'

/** Launch bounty pool. Hourly boards sample from this list. */
export const BOUNTY_CATALOG: BountyDefinition[] = [
  {
    id: 'BNT-0001',
    title: 'Root Runner',
    description: 'Gather Wild Roots.',
    kind: 'gather_item',
    targetId: 'ITEM-0030',
    amount: 8,
    rewardGold: 40,
  },
  {
    id: 'BNT-0002',
    title: 'Fernleaf Forager',
    description: 'Gather Fernleaf.',
    kind: 'gather_item',
    targetId: 'ITEM-0031',
    amount: 8,
    rewardGold: 40,
  },
  {
    id: 'BNT-0003',
    title: 'Copper Quota',
    description: 'Mine Copper Ore.',
    kind: 'gather_item',
    targetId: 'ITEM-0003',
    amount: 10,
    rewardGold: 55,
  },
  {
    id: 'BNT-0004',
    title: 'Clay Haul',
    description: 'Dig Clay.',
    kind: 'gather_item',
    targetId: 'ITEM-0002',
    amount: 12,
    rewardGold: 45,
  },
  {
    id: 'BNT-0005',
    title: 'Pasture Patrol',
    description: 'Defeat Cows.',
    kind: 'defeat_enemy',
    targetId: 'ENM-0001',
    amount: 5,
    rewardGold: 50,
  },
  {
    id: 'BNT-0006',
    title: 'Bull Buster',
    description: 'Defeat Bulls.',
    kind: 'defeat_enemy',
    targetId: 'ENM-0002',
    amount: 2,
    rewardGold: 70,
  },
  {
    id: 'BNT-0007',
    title: 'Scout Sweep',
    description: 'Defeat Goblin Scouts.',
    kind: 'defeat_enemy',
    targetId: 'ENM-0003',
    amount: 4,
    rewardGold: 80,
  },
  {
    id: 'BNT-0008',
    title: 'Kitchen Duty',
    description: 'Cook Baked Potatoes.',
    kind: 'process_recipe',
    targetId: 'RCP-0001',
    amount: 5,
    rewardGold: 60,
  },
  {
    id: 'BNT-0009',
    title: 'Crawfish Cook',
    description: 'Cook Cooked Crawfish.',
    kind: 'process_recipe',
    targetId: 'RCP-0002',
    amount: 3,
    rewardGold: 65,
  },
  {
    id: 'BNT-0010',
    title: 'Trout Tray',
    description: 'Cook Cooked Trout.',
    kind: 'process_recipe',
    targetId: 'RCP-0003',
    amount: 3,
    rewardGold: 70,
  },
]

export const BOUNTIES_PER_HOUR = 3
