/// Pure Dart port of the Idle Kingdoms rules in `src/game`.
///
/// Nothing here may import `dart:io`, `dart:html`, or Flutter: the rules stay
/// testable headlessly and identically to the TypeScript original. Time and
/// randomness are always parameters, never ambient globals.
///
/// Generated save models define no `==`; compare them through `toJson`, which is
/// also how the parity fixtures check them.
library;

export 'src/achievements/progress.dart';
export 'src/activity/bonus_xp.dart';
export 'src/activity/engine.dart';
export 'src/activity/favorites.dart';
export 'src/activity/gathering.dart';
export 'src/activity/held_action.dart';
export 'src/activity/pools.dart';
export 'src/activity/requirements.dart';
export 'src/activity/reward_summary.dart';
export 'src/activity/rewards.dart';
export 'src/activity/transition.dart';
export 'src/activity/types.dart';
export 'src/activity/xp.dart';
export 'src/activity/xp_progress.dart';
export 'src/bounties/catalog.dart';
export 'src/bounties/complete.dart';
export 'src/bounties/progress.dart';
export 'src/bounties/rotation.dart';
export 'src/bounties/types.dart';
export 'src/bounties/views.dart';
export 'src/combat/engine.dart';
export 'src/combat/food.dart';
export 'src/combat/pvp.dart';
export 'src/combat/stats.dart';
export 'src/combat/summary.dart';
export 'src/config.dart';
export 'src/cosmetics/appearance.dart';
export 'src/cosmetics/cosmetics.dart';
export 'src/cosmetics/wardrobe.dart';
export 'src/critters/critters.dart';
export 'src/equipment/auto_equip.dart';
export 'src/equipment/loadout.dart';
export 'src/equipment/tooltips.dart';
export 'src/equipment/vitals.dart';
export 'src/guild/hall.dart';
export 'src/inventory/add_items.dart';
export 'src/inventory/bank.dart';
export 'src/inventory/capacity.dart';
export 'src/inventory/destroy.dart';
export 'src/inventory/favorites.dart';
export 'src/inventory/gold.dart';
export 'src/inventory/sell.dart';
export 'src/js_compat.dart';
export 'src/json_support.dart';
export 'src/log/log.dart';
export 'src/loot/drop_chance.dart';
export 'src/npcs/conversation.dart';
export 'src/npcs/knowledge.dart';
export 'src/potions/effects.dart';
export 'src/production/engine.dart';
export 'src/production/inventory.dart';
export 'src/production/recipes.dart';
export 'src/projects/enchantments.dart';
export 'src/projects/engine.dart';
export 'src/projects/menu.dart';
export 'src/projects/projects.dart';
export 'src/pvp/arena.dart';
export 'src/pvp/matchmaking.dart';
export 'src/quests/objectives.dart';
export 'src/quests/progress.dart';
export 'src/quests/quests.dart';
export 'src/races/assign_race.dart';
export 'src/races/races.dart';
export 'src/recipes/knowledge.dart';
export 'src/rng/mulberry32.dart';
export 'src/save/character_name.dart';
export 'src/save/generated/save_models.dart';
export 'src/save/json_save.dart';
export 'src/save/migrations.dart';
export 'src/save/player_title.dart';
export 'src/save/save_store.dart';
export 'src/save/starting_gear.dart';
export 'src/shops/quantity.dart';
export 'src/shops/shops.dart';
export 'src/shops/transactions.dart';
export 'src/skills/skill_actions.dart';
export 'src/skills/totals.dart';
export 'src/spells/spells.dart';
export 'src/tags.dart';
export 'src/time.dart';
export 'src/unattended/resolve.dart';
export 'src/unattended/summary.dart';
export 'src/world/amenity_copy.dart';
export 'src/world/blessing.dart';
export 'src/world/constants.dart';
export 'src/world/hostility.dart';
export 'src/world/location_search.dart';
export 'src/world/map_label.dart';
export 'src/world/map_layout.dart';
export 'src/world/submaps.dart';
export 'src/world/travel.dart';
